# Generated by Django 4.2.6 on 2023-12-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("currPlayer_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Square",
            fields=[
                ("square_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=10)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameinterface.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_index", models.AutoField(primary_key=True, serialize=False)),
                ("player_id", models.IntegerField(blank=True, null=True)),
                ("player_name", models.CharField(max_length=15)),
                ("color", models.CharField(max_length=10)),
                ("isAI", models.BooleanField()),
                ("isHuman", models.BooleanField()),
                ("isReady", models.BooleanField()),
                ("hasSurrendered", models.BooleanField()),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameinterface.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KI",
            fields=[
                ("ki_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "blocks_array",
                    models.TextField(
                        default="[[[false, false, false, false, false], [false, false, false, false, false], [false, false, true, false, false], [false, false, false, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, false, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, false, false, false], [false, false, true, false, false], [false, false, true, true, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, true, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, true, false], [false, false, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, false, false, false], [false, true, true, false, false], [false, true, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, false, false, false], [false, true, true, false, false], [false, false, true, true, false], [false, false, false, false, false]], [[false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false]], [[false, false, true, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, true, true, false, false], [false, false, false, false, false]], [[false, false, true, false, false], [false, false, true, false, false], [false, true, true, false, false], [false, true, false, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, true, true, false, false], [false, true, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, true, true, false, false], [false, false, true, false, false], [false, true, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, true, false], [false, false, true, false, false], [false, false, true, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, false, true, false, false], [false, true, true, true, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, true, false, false, false], [false, true, false, false, false], [false, true, true, true, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, true, true, false, false], [false, false, true, true, false], [false, false, false, true, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, true, false, false, false], [false, true, true, true, false], [false, false, false, true, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, true, false, false, false], [false, true, true, true, false], [false, false, true, false, false], [false, false, false, false, false]], [[false, false, false, false, false], [false, false, true, false, false], [false, true, true, true, false], [false, false, true, false, false], [false, false, false, false, false]]]"
                    ),
                ),
                (
                    "player_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameinterface.player",
                    ),
                ),
            ],
        ),
    ]
