# Generated by Django 4.2.6 on 2023-11-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Square",
            fields=[
                ("square_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=10)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameinterface.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(max_length=10)),
                ("isAI", models.BooleanField()),
                ("isHuman", models.BooleanField()),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameinterface.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="currPlayer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gameinterface.player"
            ),
        ),
    ]
