# Generated by Django 4.2.6 on 2023-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameinterface", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="currPlayer_id",
            field=models.IntegerField(),
        ),
    ]
