# Generated by Django 4.2.6 on 2023-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameinterface", "0002_alter_player_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="hasSurrendered",
            field=models.BooleanField(default=False),
        ),
    ]
