# Generated by Django 4.2.6 on 2023-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameinterface", "0003_player_hassurrendered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="hasSurrendered",
            field=models.BooleanField(),
        ),
    ]
